Models/Contexts/DataContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore;
using WebIntroEmpty.Models.Entities;

namespace WebIntroEmpty.Models.Contexts
{
    public class DataContext : DbContext
    {

        public DataContext(DbContextOptions options)
            :base(options){ 
        }
        

        public DbSet<Country> Countries { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

          
         
        }
    }
}

Models/Contexts/DataSeed.cs
using WebIntroEmpty.Models.Entities;

namespace WebIntroEmpty.Models.Contexts
{
    public static class DataSeed
    {

        internal static IApplicationBuilder Seed(this IApplicationBuilder app)
        {
            using (var scope = app.ApplicationServices.CreateScope())
            {
                var db = scope.ServiceProvider.GetRequiredService<DataContext>();

                var list = new[]
                {
                new Country { Id=1,Name = "Azerbaijan", Code = "AZE" },
                new Country { Id=2,Name = "Russia", Code = "RU" },
                new Country { Id = 3, Name = "Turkey", Code = "TR" },
                new Country { Id = 4, Name = "Georgia", Code = "GRE" }



            };


                db.Countries.AddRange(list);

                db.SaveChanges();
            }
            return app;
        }
    }
}

Models/Entities/Country.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebIntroEmpty.Models.Entities
{
    public class Country
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int Id { get; set; }

        public required string Name { get; set; }

        public required string Code { get; set; }
    }
}

Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Metrics;
using WebIntroEmpty.Models.Contexts;
using WebIntroEmpty.Models.Entities;

namespace WebIntroEmpty.Controllers
{
    public class CountriesController : Controller
    {
        private readonly DataContext db;

        public CountriesController(DataContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {

            var countries = db.Countries.ToList();

            return View(countries);


        }

        public IActionResult Details(int id)
        {
            var country = db.Countries.Where(m => m.Id == id).FirstOrDefault();

            return View(country);

        }

        public IActionResult Edit(int id)
        {
            var country = db.Countries.Where(m => m.Id == id).FirstOrDefault();

            return View(country);

        }

        [HttpPost]
        public IActionResult Edit(Country model)
        {
            db.Entry(model).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Country model)
        {
            db.Countries.Add(model);
            db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int id)
        {
            var student = db.Countries.Where(m => m.Id == id).FirstOrDefault();


            db.Countries.Remove(student);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebIntroEmpty.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }



    }
}

Views/Countries/Create.cshtml
@model Country
@{
    Layout = "_Layout";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div class="row">
        <div class="col-12">
            <form method="post">
                <div class="mb-3">
                    <label asp-for="Name" class="form-label">Name</label>
                    <input class="form-control" asp-for="Name" aria-describedby="nameHelp">
                    <div id="nameHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                    <label asp-for="Code" class="form-label">Code</label>
                    <input class="form-control" asp-for="Code" aria-describedby="surnameHelp">
                    <div id="surnameHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <button type="submit" class="btn btn-primary">Yadda saxla</button>
            </form>
        </div>
    </div>


</body>
</html>

Views/Countries/Details.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <dl>
        <dt>Name</dt>
        <dd>@Model.Name</dd>

        <dt>Surname</dt>
        <dd>@Model.Code</dd>

    </dl>
    <a asp-controller="Countries" asp-action="index">Go back</a>


</body>
</html>

Views/Countries/Edit.cshtml
@model Country
@{
    Layout = "_Layout";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>


    <div class="row">
        <div class="col-12">
            <form method="post">
                <div class="mb-3">
                    <label asp-for="Name" class="form-label">Name</label>
                    <input class="form-control" asp-for="Name" aria-describedby="nameHelp">
                    <div id="nameHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                    <label asp-for="Code" class="form-label">Surname</label>
                    <input class="form-control" asp-for="Code" aria-describedby="surnameHelp">
                    <div id="surnameHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <input asp-for="Id" hidden />
                <button type="submit" class="btn btn-primary">Yadda saxla</button>
            </form>
        </div>
    </div>


</body>
</html>

Views/Countries/Index.cshtml
@model List<Country>
@{
    Layout = "_Layout";
}


<div class="row">
    <div class="col-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>

                    <th>
                        Code
                    </th>
                    <th>
                        <a asp-controller="Countries" asp-action="Create">Create new</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>

                        <td>
                            @item.Code
                        </td>
                        <td>
                            <a asp-controller="Countries" asp-action="Details" asp-route-id="@item.Id">Details</a>
                            <a asp-controller="Countries" asp-action="edit" asp-route-id="@item.Id">Edit</a>
                            <a asp-controller="Countries" asp-action="remove" asp-route-id="@item.Id">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/assets/css/style.css" />
</head>
<body>
    <h1>Home/Index</h1>
    <div class="box"></div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"  />
</head>
<body>


    @RenderBody()

    </body>
    </html>